language: cpp
sudo: required

install:
  - curl http://ubuntu.openturns.org/openturns.org-repo.key | sudo apt-key add -
  - echo deb http://ubuntu.openturns.org precise main | sudo tee /etc/apt/sources.list.d/openturns.list
  - sudo apt-get update
  - sudo apt-get -y install python-openturns python-sphinx python-nose python-numpy
  - pip install joblib ipyparallel pathos numpydoc alabaster --user

script:
  - nosetests
  - python setup.py install --user
  - cd doc && make html
